// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	BenchmarkMetrics string
	Floors           string
	IotDevices       string
	SchemaMigrations string
	SensorReadings   string
	Users            string
	Zones            string
}{
	BenchmarkMetrics: "benchmark_metrics",
	Floors:           "floors",
	IotDevices:       "iot_devices",
	SchemaMigrations: "schema_migrations",
	SensorReadings:   "sensor_readings",
	Users:            "users",
	Zones:            "zones",
}
