// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// SensorReading is an object representing the database table.
type SensorReading struct {
	ID              int64        `boil:"id" json:"id" toml:"id" yaml:"id"`
	DeviceID        string       `boil:"device_id" json:"device_id" toml:"device_id" yaml:"device_id"`
	DeviceName      string       `boil:"device_name" json:"device_name" toml:"device_name" yaml:"device_name"`
	DeviceType      string       `boil:"device_type" json:"device_type" toml:"device_type" yaml:"device_type"`
	Location        string       `boil:"location" json:"location" toml:"location" yaml:"location"`
	FloorID         int          `boil:"floor_id" json:"floor_id" toml:"floor_id" yaml:"floor_id"`
	ZoneID          int          `boil:"zone_id" json:"zone_id" toml:"zone_id" yaml:"zone_id"`
	Temperature     float64      `boil:"temperature" json:"temperature" toml:"temperature" yaml:"temperature"`
	Humidity        float64      `boil:"humidity" json:"humidity" toml:"humidity" yaml:"humidity"`
	Co2             float64      `boil:"co2" json:"co2" toml:"co2" yaml:"co2"`
	Timestamp       time.Time    `boil:"timestamp" json:"timestamp" toml:"timestamp" yaml:"timestamp"`
	CreatedAt       null.Time    `boil:"created_at" json:"created_at,omitempty" toml:"created_at" yaml:"created_at,omitempty"`
	DurableWriteTS  time.Time    `boil:"durable_write_ts" json:"durable_write_ts" toml:"durable_write_ts" yaml:"durable_write_ts"`
	HeatIndex       null.Float64 `boil:"heat_index" json:"heat_index,omitempty" toml:"heat_index" yaml:"heat_index,omitempty"`
	AirQualityIndex null.Int     `boil:"air_quality_index" json:"air_quality_index,omitempty" toml:"air_quality_index" yaml:"air_quality_index,omitempty"`

	R *sensorReadingR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L sensorReadingL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var SensorReadingColumns = struct {
	ID              string
	DeviceID        string
	DeviceName      string
	DeviceType      string
	Location        string
	FloorID         string
	ZoneID          string
	Temperature     string
	Humidity        string
	Co2             string
	Timestamp       string
	CreatedAt       string
	DurableWriteTS  string
	HeatIndex       string
	AirQualityIndex string
}{
	ID:              "id",
	DeviceID:        "device_id",
	DeviceName:      "device_name",
	DeviceType:      "device_type",
	Location:        "location",
	FloorID:         "floor_id",
	ZoneID:          "zone_id",
	Temperature:     "temperature",
	Humidity:        "humidity",
	Co2:             "co2",
	Timestamp:       "timestamp",
	CreatedAt:       "created_at",
	DurableWriteTS:  "durable_write_ts",
	HeatIndex:       "heat_index",
	AirQualityIndex: "air_quality_index",
}

var SensorReadingTableColumns = struct {
	ID              string
	DeviceID        string
	DeviceName      string
	DeviceType      string
	Location        string
	FloorID         string
	ZoneID          string
	Temperature     string
	Humidity        string
	Co2             string
	Timestamp       string
	CreatedAt       string
	DurableWriteTS  string
	HeatIndex       string
	AirQualityIndex string
}{
	ID:              "sensor_readings.id",
	DeviceID:        "sensor_readings.device_id",
	DeviceName:      "sensor_readings.device_name",
	DeviceType:      "sensor_readings.device_type",
	Location:        "sensor_readings.location",
	FloorID:         "sensor_readings.floor_id",
	ZoneID:          "sensor_readings.zone_id",
	Temperature:     "sensor_readings.temperature",
	Humidity:        "sensor_readings.humidity",
	Co2:             "sensor_readings.co2",
	Timestamp:       "sensor_readings.timestamp",
	CreatedAt:       "sensor_readings.created_at",
	DurableWriteTS:  "sensor_readings.durable_write_ts",
	HeatIndex:       "sensor_readings.heat_index",
	AirQualityIndex: "sensor_readings.air_quality_index",
}

// Generated where

type whereHelpernull_Int struct{ field string }

func (w whereHelpernull_Int) EQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int) NEQ(x null.Int) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int) LT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int) LTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int) GT(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int) GTE(x null.Int) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int) IN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int) NIN(slice []int) qm.QueryMod {
	values := make([]interface{}, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

var SensorReadingWhere = struct {
	ID              whereHelperint64
	DeviceID        whereHelperstring
	DeviceName      whereHelperstring
	DeviceType      whereHelperstring
	Location        whereHelperstring
	FloorID         whereHelperint
	ZoneID          whereHelperint
	Temperature     whereHelperfloat64
	Humidity        whereHelperfloat64
	Co2             whereHelperfloat64
	Timestamp       whereHelpertime_Time
	CreatedAt       whereHelpernull_Time
	DurableWriteTS  whereHelpertime_Time
	HeatIndex       whereHelpernull_Float64
	AirQualityIndex whereHelpernull_Int
}{
	ID:              whereHelperint64{field: "\"sensor_readings\".\"id\""},
	DeviceID:        whereHelperstring{field: "\"sensor_readings\".\"device_id\""},
	DeviceName:      whereHelperstring{field: "\"sensor_readings\".\"device_name\""},
	DeviceType:      whereHelperstring{field: "\"sensor_readings\".\"device_type\""},
	Location:        whereHelperstring{field: "\"sensor_readings\".\"location\""},
	FloorID:         whereHelperint{field: "\"sensor_readings\".\"floor_id\""},
	ZoneID:          whereHelperint{field: "\"sensor_readings\".\"zone_id\""},
	Temperature:     whereHelperfloat64{field: "\"sensor_readings\".\"temperature\""},
	Humidity:        whereHelperfloat64{field: "\"sensor_readings\".\"humidity\""},
	Co2:             whereHelperfloat64{field: "\"sensor_readings\".\"co2\""},
	Timestamp:       whereHelpertime_Time{field: "\"sensor_readings\".\"timestamp\""},
	CreatedAt:       whereHelpernull_Time{field: "\"sensor_readings\".\"created_at\""},
	DurableWriteTS:  whereHelpertime_Time{field: "\"sensor_readings\".\"durable_write_ts\""},
	HeatIndex:       whereHelpernull_Float64{field: "\"sensor_readings\".\"heat_index\""},
	AirQualityIndex: whereHelpernull_Int{field: "\"sensor_readings\".\"air_quality_index\""},
}

// SensorReadingRels is where relationship names are stored.
var SensorReadingRels = struct {
	Floor string
	Zone  string
}{
	Floor: "Floor",
	Zone:  "Zone",
}

// sensorReadingR is where relationships are stored.
type sensorReadingR struct {
	Floor *Floor `boil:"Floor" json:"Floor" toml:"Floor" yaml:"Floor"`
	Zone  *Zone  `boil:"Zone" json:"Zone" toml:"Zone" yaml:"Zone"`
}

// NewStruct creates a new relationship struct
func (*sensorReadingR) NewStruct() *sensorReadingR {
	return &sensorReadingR{}
}

func (o *SensorReading) GetFloor() *Floor {
	if o == nil {
		return nil
	}

	return o.R.GetFloor()
}

func (r *sensorReadingR) GetFloor() *Floor {
	if r == nil {
		return nil
	}

	return r.Floor
}

func (o *SensorReading) GetZone() *Zone {
	if o == nil {
		return nil
	}

	return o.R.GetZone()
}

func (r *sensorReadingR) GetZone() *Zone {
	if r == nil {
		return nil
	}

	return r.Zone
}

// sensorReadingL is where Load methods for each relationship are stored.
type sensorReadingL struct{}

var (
	sensorReadingAllColumns            = []string{"id", "device_id", "device_name", "device_type", "location", "floor_id", "zone_id", "temperature", "humidity", "co2", "timestamp", "created_at", "durable_write_ts", "heat_index", "air_quality_index"}
	sensorReadingColumnsWithoutDefault = []string{"device_id", "device_name", "device_type", "location", "floor_id", "zone_id"}
	sensorReadingColumnsWithDefault    = []string{"id", "temperature", "humidity", "co2", "timestamp", "created_at", "durable_write_ts", "heat_index", "air_quality_index"}
	sensorReadingPrimaryKeyColumns     = []string{"id", "timestamp"}
	sensorReadingGeneratedColumns      = []string{"heat_index", "air_quality_index"}
)

type (
	// SensorReadingSlice is an alias for a slice of pointers to SensorReading.
	// This should almost always be used instead of []SensorReading.
	SensorReadingSlice []*SensorReading

	sensorReadingQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	sensorReadingType                 = reflect.TypeOf(&SensorReading{})
	sensorReadingMapping              = queries.MakeStructMapping(sensorReadingType)
	sensorReadingPrimaryKeyMapping, _ = queries.BindMapping(sensorReadingType, sensorReadingMapping, sensorReadingPrimaryKeyColumns)
	sensorReadingInsertCacheMut       sync.RWMutex
	sensorReadingInsertCache          = make(map[string]insertCache)
	sensorReadingUpdateCacheMut       sync.RWMutex
	sensorReadingUpdateCache          = make(map[string]updateCache)
	sensorReadingUpsertCacheMut       sync.RWMutex
	sensorReadingUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single sensorReading record from the query.
func (q sensorReadingQuery) One(ctx context.Context, exec boil.ContextExecutor) (*SensorReading, error) {
	o := &SensorReading{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: failed to execute a one query for sensor_readings")
	}

	return o, nil
}

// All returns all SensorReading records from the query.
func (q sensorReadingQuery) All(ctx context.Context, exec boil.ContextExecutor) (SensorReadingSlice, error) {
	var o []*SensorReading

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "dbmodel: failed to assign all query results to SensorReading slice")
	}

	return o, nil
}

// Count returns the count of all SensorReading records in the query.
func (q sensorReadingQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to count sensor_readings rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q sensorReadingQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: failed to check if sensor_readings exists")
	}

	return count > 0, nil
}

// Floor pointed to by the foreign key.
func (o *SensorReading) Floor(mods ...qm.QueryMod) floorQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FloorID),
	}

	queryMods = append(queryMods, mods...)

	return Floors(queryMods...)
}

// Zone pointed to by the foreign key.
func (o *SensorReading) Zone(mods ...qm.QueryMod) zoneQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ZoneID),
	}

	queryMods = append(queryMods, mods...)

	return Zones(queryMods...)
}

// LoadFloor allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sensorReadingL) LoadFloor(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSensorReading interface{}, mods queries.Applicator) error {
	var slice []*SensorReading
	var object *SensorReading

	if singular {
		var ok bool
		object, ok = maybeSensorReading.(*SensorReading)
		if !ok {
			object = new(SensorReading)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSensorReading)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSensorReading))
			}
		}
	} else {
		s, ok := maybeSensorReading.(*[]*SensorReading)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSensorReading)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSensorReading))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &sensorReadingR{}
		}
		args[object.FloorID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sensorReadingR{}
			}

			args[obj.FloorID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`floors`),
		qm.WhereIn(`floors.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Floor")
	}

	var resultSlice []*Floor
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Floor")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for floors")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for floors")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Floor = foreign
		if foreign.R == nil {
			foreign.R = &floorR{}
		}
		foreign.R.SensorReadings = append(foreign.R.SensorReadings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FloorID == foreign.ID {
				local.R.Floor = foreign
				if foreign.R == nil {
					foreign.R = &floorR{}
				}
				foreign.R.SensorReadings = append(foreign.R.SensorReadings, local)
				break
			}
		}
	}

	return nil
}

// LoadZone allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (sensorReadingL) LoadZone(ctx context.Context, e boil.ContextExecutor, singular bool, maybeSensorReading interface{}, mods queries.Applicator) error {
	var slice []*SensorReading
	var object *SensorReading

	if singular {
		var ok bool
		object, ok = maybeSensorReading.(*SensorReading)
		if !ok {
			object = new(SensorReading)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeSensorReading)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeSensorReading))
			}
		}
	} else {
		s, ok := maybeSensorReading.(*[]*SensorReading)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeSensorReading)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeSensorReading))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &sensorReadingR{}
		}
		args[object.ZoneID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &sensorReadingR{}
			}

			args[obj.ZoneID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`zones`),
		qm.WhereIn(`zones.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Zone")
	}

	var resultSlice []*Zone
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Zone")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for zones")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for zones")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Zone = foreign
		if foreign.R == nil {
			foreign.R = &zoneR{}
		}
		foreign.R.SensorReadings = append(foreign.R.SensorReadings, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ZoneID == foreign.ID {
				local.R.Zone = foreign
				if foreign.R == nil {
					foreign.R = &zoneR{}
				}
				foreign.R.SensorReadings = append(foreign.R.SensorReadings, local)
				break
			}
		}
	}

	return nil
}

// SetFloor of the sensorReading to the related item.
// Sets o.R.Floor to related.
// Adds o to related.R.SensorReadings.
func (o *SensorReading) SetFloor(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Floor) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"sensor_readings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"floor_id"}),
		strmangle.WhereClause("\"", "\"", 2, sensorReadingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID, o.Timestamp}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FloorID = related.ID
	if o.R == nil {
		o.R = &sensorReadingR{
			Floor: related,
		}
	} else {
		o.R.Floor = related
	}

	if related.R == nil {
		related.R = &floorR{
			SensorReadings: SensorReadingSlice{o},
		}
	} else {
		related.R.SensorReadings = append(related.R.SensorReadings, o)
	}

	return nil
}

// SetZone of the sensorReading to the related item.
// Sets o.R.Zone to related.
// Adds o to related.R.SensorReadings.
func (o *SensorReading) SetZone(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Zone) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"sensor_readings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"zone_id"}),
		strmangle.WhereClause("\"", "\"", 2, sensorReadingPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID, o.Timestamp}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ZoneID = related.ID
	if o.R == nil {
		o.R = &sensorReadingR{
			Zone: related,
		}
	} else {
		o.R.Zone = related
	}

	if related.R == nil {
		related.R = &zoneR{
			SensorReadings: SensorReadingSlice{o},
		}
	} else {
		related.R.SensorReadings = append(related.R.SensorReadings, o)
	}

	return nil
}

// SensorReadings retrieves all the records using an executor.
func SensorReadings(mods ...qm.QueryMod) sensorReadingQuery {
	mods = append(mods, qm.From("\"sensor_readings\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"sensor_readings\".*"})
	}

	return sensorReadingQuery{q}
}

// FindSensorReading retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindSensorReading(ctx context.Context, exec boil.ContextExecutor, iD int64, timestamp time.Time, selectCols ...string) (*SensorReading, error) {
	sensorReadingObj := &SensorReading{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"sensor_readings\" where \"id\"=$1 AND \"timestamp\"=$2", sel,
	)

	q := queries.Raw(query, iD, timestamp)

	err := q.Bind(ctx, exec, sensorReadingObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "dbmodel: unable to select from sensor_readings")
	}

	return sensorReadingObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *SensorReading) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("dbmodel: no sensor_readings provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(sensorReadingColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	sensorReadingInsertCacheMut.RLock()
	cache, cached := sensorReadingInsertCache[key]
	sensorReadingInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			sensorReadingAllColumns,
			sensorReadingColumnsWithDefault,
			sensorReadingColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, sensorReadingGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(sensorReadingType, sensorReadingMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(sensorReadingType, sensorReadingMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"sensor_readings\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"sensor_readings\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to insert into sensor_readings")
	}

	if !cached {
		sensorReadingInsertCacheMut.Lock()
		sensorReadingInsertCache[key] = cache
		sensorReadingInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the SensorReading.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *SensorReading) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	sensorReadingUpdateCacheMut.RLock()
	cache, cached := sensorReadingUpdateCache[key]
	sensorReadingUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			sensorReadingAllColumns,
			sensorReadingPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, sensorReadingGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("dbmodel: unable to update sensor_readings, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"sensor_readings\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, sensorReadingPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(sensorReadingType, sensorReadingMapping, append(wl, sensorReadingPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update sensor_readings row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by update for sensor_readings")
	}

	if !cached {
		sensorReadingUpdateCacheMut.Lock()
		sensorReadingUpdateCache[key] = cache
		sensorReadingUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q sensorReadingQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all for sensor_readings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected for sensor_readings")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o SensorReadingSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("dbmodel: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sensorReadingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"sensor_readings\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, sensorReadingPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to update all in sensorReading slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to retrieve rows affected all in update all sensorReading")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *SensorReading) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("dbmodel: no sensor_readings provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if queries.MustTime(o.CreatedAt).IsZero() {
			queries.SetScanner(&o.CreatedAt, currTime)
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(sensorReadingColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	sensorReadingUpsertCacheMut.RLock()
	cache, cached := sensorReadingUpsertCache[key]
	sensorReadingUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			sensorReadingAllColumns,
			sensorReadingColumnsWithDefault,
			sensorReadingColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			sensorReadingAllColumns,
			sensorReadingPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, sensorReadingGeneratedColumns)
		update = strmangle.SetComplement(update, sensorReadingGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("dbmodel: unable to upsert sensor_readings, could not build update column list")
		}

		ret := strmangle.SetComplement(sensorReadingAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(sensorReadingPrimaryKeyColumns) == 0 {
				return errors.New("dbmodel: unable to upsert sensor_readings, could not build conflict column list")
			}

			conflict = make([]string, len(sensorReadingPrimaryKeyColumns))
			copy(conflict, sensorReadingPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"sensor_readings\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(sensorReadingType, sensorReadingMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(sensorReadingType, sensorReadingMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to upsert sensor_readings")
	}

	if !cached {
		sensorReadingUpsertCacheMut.Lock()
		sensorReadingUpsertCache[key] = cache
		sensorReadingUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single SensorReading record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *SensorReading) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("dbmodel: no SensorReading provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), sensorReadingPrimaryKeyMapping)
	sql := "DELETE FROM \"sensor_readings\" WHERE \"id\"=$1 AND \"timestamp\"=$2"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete from sensor_readings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by delete for sensor_readings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q sensorReadingQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("dbmodel: no sensorReadingQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from sensor_readings")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for sensor_readings")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o SensorReadingSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []interface{}
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sensorReadingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"sensor_readings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sensorReadingPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: unable to delete all from sensorReading slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "dbmodel: failed to get rows affected by deleteall for sensor_readings")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *SensorReading) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindSensorReading(ctx, exec, o.ID, o.Timestamp)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *SensorReadingSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := SensorReadingSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), sensorReadingPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"sensor_readings\".* FROM \"sensor_readings\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, sensorReadingPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "dbmodel: unable to reload all in SensorReadingSlice")
	}

	*o = slice

	return nil
}

// SensorReadingExists checks if the SensorReading row exists.
func SensorReadingExists(ctx context.Context, exec boil.ContextExecutor, iD int64, timestamp time.Time) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"sensor_readings\" where \"id\"=$1 AND \"timestamp\"=$2 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD, timestamp)
	}
	row := exec.QueryRowContext(ctx, sql, iD, timestamp)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "dbmodel: unable to check if sensor_readings exists")
	}

	return exists, nil
}

// Exists checks if the SensorReading row exists.
func (o *SensorReading) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return SensorReadingExists(ctx, exec, o.ID, o.Timestamp)
}
